title: Wiki.chairat.me
description: 
show_downloads: false
google_analytics: UA-89685926-4
theme: jekyll-theme-cayman
blog_url: http://chairat.me
github: 
  is_project_page: true
  repository_url: https://github.com/pacroy/pacroy.github.io
  repository_name: Wiki.chairat.me
  owner_url: https://github.com/pacroy/
  owner_name: Chairat (Par)